project_id = "fswujhlgnhnjuldpnjmt"

[functions.chat]
verify_jwt = false

[functions.ingest-pdf]
verify_jwt = false

[functions.process-embeddings]
verify_jwt = false

[functions.ingest-knowledge]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false
